require 'rake/testtask'
require 'rubocop/rake_task'
require 'reek/rake/task'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_test.rb']
end

Rake::TestTask.new(:bench) do |t|
  t.pattern = '*_benchmark.rb'
end

RuboCop::RakeTask.new(:rubocop) do |t|
  # task.patterns = [
  #   'lib/**/*.rb',
  #   'test/**/*.rb'
  # ]
end

Reek::Rake::Task.new do |t|
  # t.config_file = 'config.reek'
  # t.source_files = '**/*.rb'
  t.reek_opts = '--sort-by smelliness --no-progress -s'
end

task quality: %i[rubocop reek]

task default: %i[test quality]
